[package]
name = "court-node"
version = "0.1.0"
edition = "2021"
description = "YAML SmartContracts++ - Revolutionary CUE-powered smart contract engine"
authors = ["Metanode Team"]
license = "MIT"

[dependencies]
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
serde_json = "1.0"
tokio = { version = "1.0", features = ["full"] }
tracing = "0.1"
uuid = { version = "1.0", features = ["v4"] }
md5 = "0.7"
chrono = { version = "0.4", features = ["serde"] }
sha2 = "0.10"
ed25519-dalek = "2.0"
rand = "0.8"
regex = "1.0"
indexmap = "2.0"

# CUE integration (using cue-rs for CUE language support)
# Note: In production, this would integrate with actual CUE runtime
# For now, we'll implement a CUE-compatible YAML processor

# Internal dependencies
court-notary-registry = { path = "../court-notary-registry" }

[dev-dependencies]
tokio-test = "0.4"
tempfile = "3.0"

[[bin]]
name = "court-node-cli"
path = "src/bin/court_node_cli.rs"

[[bin]]
name = "yaml-contract-compiler"
path = "src/bin/yaml_contract_compiler.rs"
