[package]
name = "http-cage"
version = "0.1.0"
edition = "2021"
description = "Military-grade HTTP security layer for Metanode platform (9.5/10 security)"

[dependencies]
# HTTP and networking
hyper = { version = "1.0", features = ["full"] }
hyper-util = { version = "0.1", features = ["full"] }
tokio = { version = "1.0", features = ["full"] }
tower = "0.4"
tower-http = { version = "0.5", features = ["trace", "timeout", "compression-gzip"] }

# TLS and cryptography
rustls = "0.21"
rustls-pemfile = "1.0"
tokio-rustls = "0.24"
ed25519-dalek = { version = "1.0", features = ["serde"] }
x25519-dalek = { version = "1.0", features = ["serde"] }
chacha20poly1305 = "0.10"
blake3 = "1.0"

# Serialization and data handling
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.9"
bincode = "1.0"

# ZIPLOCK-JSON comprehensive audit integration
ziplock-json = { path = "../../ziplock-json" }

# HTTP parsing and validation
httparse = "1.0"
http = "1.0"
mime = "0.3"
url = "2.0"

# Async and futures
futures = "0.3"
async-trait = "0.1"

# Error handling
anyhow = "1.0"
thiserror = "1.0"

# Logging and tracing
tracing = "0.1"
tracing-subscriber = "0.3"

# Time and UUID
chrono = { version = "0.4", features = ["serde"] }
uuid = { version = "1.0", features = ["v4", "serde"] }

# Configuration integration
metanode-config = { path = "../metanode-config" }

# Metrics and monitoring
prometheus = "0.13"

# Hashing and encoding
sha2 = "0.10"
hex = "0.4"
base64 = "0.22"

# Random number generation
rand = "0.7"
rand_core = "0.5"

# HTTP body utilities
http-body-util = "0.1"

# Memory protection
zeroize = "1.0"

[dev-dependencies]
tokio-test = "0.4"
tempfile = "3.0"
