[package]
name = "split-origin-auditing"
version = "0.1.0"
edition = "2021"
description = "Dual-path audit trail with client-side and server-side independent verification"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
uuid = { version = "1.0", features = ["v4", "serde"] }
chrono = { version = "0.4", features = ["serde"] }
tracing = "0.1"
thiserror = "1.0"
ed25519-dalek = { version = "2.0", features = ["rand_core"] }
rand = "0.8"
sha2 = "0.10"
hex = "0.4"
async-trait = "0.1"

# Internal dependencies
court-notary-registry = { path = "../court-notary-registry" }

[dev-dependencies]
tokio-test = "0.4"
