[package]
name = "headers-proxy"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
tokio-stream = "0.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = { version = "0.4", features = ["serde"] }
futures = "0.3"
futures-util = "0.3"
tracing = "0.1"
prometheus = "0.13"
ahash = "0.8"
lru = "0.12"
uuid = { version = "1.0", features = ["v4", "serde"] }
anyhow = "1.0"
thiserror = "1.0"

# Internal dependencies
bpi-headers = { path = "../bpi-headers" }
bpi-enc = { path = "../enc" }

[dev-dependencies]
tokio-test = "0.4"
