repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-json
      - id: pretty-format-json
        args: ['--autofix']

  - repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
      - id: fmt
        name: Rust format
      - id: clippy
        name: Rust clippy
        args: ['--workspace', '--all-targets', '--', '-D', 'warnings']

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        name: TypeScript/JSON format
        files: \.(ts|tsx|js|jsx|json|md|yml|yaml)$

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.55.0
    hooks:
      - id: eslint
        name: TypeScript lint
        files: \.(ts|tsx|js|jsx)$
        additional_dependencies:
          - eslint@8.55.0
          - '@typescript-eslint/eslint-plugin@6.13.0'
          - '@typescript-eslint/parser@6.13.0'
