[package]
name = "bpi-shadow-registry"
version = "0.1.0"
edition = "2021"
description = "Military-grade secure Web2-Web3 bridge with shadow registry for BPI Mesh"
license = "MIT OR Apache-2.0"

[dependencies]
# Core async runtime
tokio = { version = "1.0", features = ["full"] }
futures = "0.3"

# Serialization and encoding
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_with = "3.0"

# Cryptography
ed25519-dalek = { version = "2.0", features = ["rand_core"] }
x25519-dalek = "2.0"
chacha20poly1305 = "0.10"
hkdf = "0.12"
sha2 = "0.10"
rand = "0.8"
rand_core = { version = "0.6", features = ["std"] }

# Zero-Knowledge Proofs (arkworks ecosystem)
ark-groth16 = "0.4"
ark-bn254 = "0.4"
ark-ff = "0.4"
ark-ec = "0.4"
ark-std = "0.4"
ark-relations = "0.4"
ark-r1cs-std = "0.4"
ark-crypto-primitives = "0.4"

# Merkle Trees
rs_merkle = "1.4"
blake3 = "1.5"

# Networking and HTTP
reqwest = { version = "0.11", features = ["json", "rustls-tls"] }
hyper = { version = "0.14", features = ["full"] }
axum = { version = "0.6", features = ["json", "headers"] }
tower = "0.4"
tower-http = { version = "0.4", features = ["cors", "trace"] }

# Error handling and utilities
anyhow = "1.0"
thiserror = "1.0"
tracing = "0.1"
uuid = { version = "1.0", features = ["v4", "serde"] }

# Time handling
chrono = { version = "0.4", features = ["serde"] }

# Hex encoding
hex = "0.4"

# BPI dependencies
bpi-headers = { path = "../bpi-headers" }
bpi-enc = { path = "../enc" }

[dev-dependencies]
tokio-test = "0.4"
tracing-subscriber = "0.3"
