[package]
name = "bpi-bpci"
version = "0.1.0"
edition = "2021"

[dependencies]
# Real BPI Core Components
hash = { path = "../../../bpi-core/crates/metanode-core/hash" }
merkle = { path = "../../../bpi-core/crates/metanode-core/merkle" }
bpi-blsagg = { path = "../../../bpi-core/crates/blsagg" }
bpi-validator-set = { path = "../../../bpi-core/crates/metanode-consensus/bpi-validator-set" }
bpi-consensus = { path = "../../../bpi-core/crates/metanode-consensus/bpi-consensus" }
bpi-vrf = { path = "../vrf" }
autonomous-economics = { path = "../autonomous-economics" }
billing-meter = { path = "../billing-meter" }
bpi-docklock = { path = "../docklock" }

# External crates
anyhow = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["full"] }
futures = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_bytes = "0.11"
serde_cbor = { workspace = true }
serde_json = { workspace = true }
chrono = { workspace = true, features = ["serde"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
bytes = "1.5"
quinn = "0.10"
rcgen = "0.12"
rustls = "0.21"
rand = { workspace = true }
uuid = { workspace = true, features = ["v4", "serde"] }
prometheus = "0.13"
rust_decimal = "1.32"
# Cryptography for Stage 18: E2E Key Agreement
x25519-dalek = { version = "2.0", features = ["static_secrets"] }
hkdf = "0.12"
sha2 = "0.10"
hex = "0.4"

[dev-dependencies]
tokio-test = "0.4"
proptest = { workspace = true }
