[package]
name = "bpi-enc"
version = "0.1.0"
edition = "2021"
description = "Canonical encoding library for BPI with domain-separated hashing"

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
blake3 = { workspace = true }
sha2 = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
hex = "0.4"

[dev-dependencies]
proptest = { workspace = true }
