[package]
name = "bpi-math"
version = "0.1.0"
edition = "2021"
description = "Mathematical foundation for Metanode blockchain - Category Theory, Knot Theory, and Proof Systems"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
tokio = { version = "1.0", features = ["full"] }
uuid = { version = "1.0", features = ["v4"] }
anyhow = "1.0"
tracing = "0.1"
hex = "0.4"
num-bigint = "0.4"
num-traits = "0.2"
polynomial = "0.2"
bls12_381 = "0.8"
group = "0.13"
bincode = "1.3"
sha2 = "0.10"
blake3 = "1.5"
rand = "0.8"
chrono = { version = "0.4", features = ["serde"] }
ed25519-dalek = "2.0"
reqwest = { version = "0.11", features = ["json"] }
url = "2.4"

[lib]
name = "bpi_math"
path = "src/lib.rs"
