[package]
name = "bpi-docklock"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true }
tracing = { workspace = true }
tokio = { workspace = true }
blake3 = { workspace = true }
rand = { workspace = true }
rand_core = { workspace = true }

# Internal dependencies
bpi-enc = { path = "../../../../bpi-core/crates/metanode-security/bpi-enc" }
bpi-merkle = { path = "../../../../bpi-core/crates/metanode-core/merkle" }
bpi-math = { path = "../../../../bpi-core/crates/metanode-core/bpi-math" }

# Seccomp and system security
seccompiler = "0.4"
libc = "0.2"

# Serialization and hashing
bincode = "1.3"
sha2 = "0.10"
hex = "0.4"
serde_yaml = "0.9"

# RNG
rand_chacha = "0.3"

# Wallet and identity dependencies
secp256k1 = { version = "0.28", features = ["rand", "rand-std"] }
ed25519-dalek = { version = "2.0", features = ["rand_core"] }
uuid = { version = "1.0", features = ["v4", "serde"] }

# ZK and cryptography
ark-std = "0.4"
ark-ff = "0.4"
ark-ec = "0.4"

# JSON and configuration
serde_json = { workspace = true }
serde_cbor = "0.11"
toml = "0.8"

# Async utilities
futures = "0.3"
chrono = { version = "0.4", features = ["serde"] }

# Compression for witness logs
lz4 = "1.24"
zstd = "0.13"

[dev-dependencies]
tempfile = "3.8"
proptest = "1.4"
