# BPCI Server Configuration - Main ecosystem bridge
# Version: 1.0.0

[server]
name = "BPCI Main Server"
version = "1.0.0"
mode = "production"
bind_address = "0.0.0.0"
rpc_port = 8545
ws_port = 8546
api_port = 3000
dashboard_port = 8080

[network]
network = "mainnet"
p2p_port = 30303
discovery_enabled = true
max_peers = 100
bootstrap_nodes = []

[database]
postgres_url = "postgresql://bpci:bpci@localhost/bpci"
redis_url = "redis://localhost:6379"
connection_pool_size = 20

[registry]
enabled = true
authority_level = "central"
node_registration = true
identity_verification = true
kyc_required = true
aml_compliance = true

[services]
# Core services
wallet_service = true
mining_service = true
governance_service = true
notary_service = true
bridge_service = true

# Bridge services
community_bridge = true
bpi_bridge = true
enterprise_bridge = true

[bridge]
# Community node coordination
community_nodes_max = 10000
community_registration = true
community_governance = true

# BPI integration
bpi_enabled = true
bpi_mining_pools = true
bpi_rewards = true

# Enterprise coordination
enterprise_nodes = true
enterprise_compliance = true
enterprise_reporting = true

[security]
level = "production"
tls_enabled = true
rate_limiting = true
ddos_protection = true
max_requests_per_minute = 1000

[monitoring]
metrics_enabled = true
health_checks = true
log_level = "info"
prometheus_enabled = true
grafana_enabled = true

[backup]
enabled = true
interval = "daily"
retention_days = 30
backup_dir = "/var/backups/bpci-server"

[compliance]
audit_trail = true
regulatory_reporting = true
kyc_verification = true
aml_monitoring = true
