[package]
name = "bpi-receipts"
version = "0.1.0"
edition = "2021"

[dependencies]
# Core dependencies
anyhow = { workspace = true }
serde = { workspace = true }
tokio = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }

# BPI crate dependencies
bpi-enc = { path = "../../metanode-security/bpi-enc" }
bpi-blsagg = { path = "../../blsagg" }
bpi-ibft = { path = "../../metanode-consensus/ibft" }
bpi-merkle = { path = "../merkle" }
bpi-vrf = { path = "../vrf" }

# Storage and database
sqlx = { version = "0.7", features = ["runtime-tokio-rustls", "sqlite", "chrono", "uuid"] }
chrono = { version = "0.4", features = ["serde"] }
uuid = { version = "1.0", features = ["v4", "serde"] }

# Serialization
cbor4ii = "0.3"
hex = "0.4"
bincode = "1.3"
serde_bytes = "0.11"
rand = "0.8"

# Cryptography
sha2 = "0.10"

[dev-dependencies]
tempfile = "3.0"
proptest = "1.0"
rand = "0.8"
