[package]
name = "bpi-relay"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
tokio = { version = "1", features = ["rt-multi-thread", "macros", "sync", "time", "signal"] }
futures = "0.3"
rand = "0.8"
rand_chacha = "0.3"
lru = "0.12"
ahash = "0.8"
tracing = { version = "0.1", features = ["log"] }
quinn = { version = "0.10" }
rcgen = "0.11"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
bincode = "1.3"
rustls = { version = "0.21", features = ["dangerous_configuration"] }
axum = { version = "0.7", default-features = false, features = ["http1", "json", "tokio"] }
hyper = { version = "1", features = ["http1", "server"] }
prometheus = "0.13"
once_cell = "1.19"
# Military-grade storage layers
redis = { version = "0.24", features = ["tokio-comp"], optional = true }
sled = { version = "0.34", optional = true }
redb = { version = "1.5", optional = true }
clap = { version = "4.5", features = ["derive"] }
chrono = { version = "0.4", features = ["serde"] }
blake3 = "1.5"
async-trait = "0.1"

[features]
default = ["military-storage"]
# Military-grade storage features
military-storage = ["dep:redis", "dep:sled", "dep:redb"]
zip-graph = ["military-storage"]
data-chaos = ["zip-graph"]
