[package]
name = "ziplock-json"
version = "0.1.0"
edition = "2021"
description = "ZIPLOCK-JSON (ZJL) audit artifact system for Metanode VM"
license = "MIT OR Apache-2.0"

[dependencies]
# Core dependencies
anyhow = "1.0"
thiserror = "1.0"
tokio = { version = "1.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
uuid = { version = "1.0", features = ["v4"] }
blake3 = "1.5"
sha2 = "0.10"
chrono = { version = "0.4", features = ["serde"] }
hex = "0.4"

# Compression and crypto
zstd = "0.13"
chacha20poly1305 = "0.10"
ed25519-dalek = { version = "2.0", features = ["rand_core"] }
rand = "0.8"
ciborium = "0.2"

# Binary format handling
zerocopy = { version = "0.7", features = ["derive"] }
byteorder = "1.5"
varintrs = "0.2"
base64 = "0.21"

# Indexing and compression
roaring = "0.10"

# COSE signing
coset = "0.3"

# Logging
tracing = "0.1"

[dev-dependencies]
tempfile = "3.8"
tokio = { version = "1.0", features = ["full"] }
criterion = "0.5"



[features]
default = ["std"]
std = []
no_std = []
