[package]
name = "zklock-mobile-port"
version = "0.1.0"
edition = "2021"
authors = ["BPI Core Team"]
description = "ZK Merkle port system for IoT and mobile devices - lightweight DApp infrastructure"
license = "MIT OR Apache-2.0"
repository = "https://github.com/bpi-core/zklock-mobile-port"
keywords = ["blockchain", "zero-knowledge", "iot", "mobile", "merkle"]
categories = ["cryptography", "embedded", "network-programming"]

[dependencies]
# Core async runtime
tokio = { version = "1.0", features = ["full"] }
anyhow = "1.0"
thiserror = "1.0"
tracing = "0.1"
tracing-subscriber = "0.3"

# Cryptography and ZK proofs
sha2 = "0.10"
blake3 = "1.5"
ed25519-dalek = "2.0"
rand = "0.8"
hex = "0.4"

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
bincode = "1.3"

# Networking
reqwest = { version = "0.11", features = ["json"] }
tokio-tungstenite = "0.20"
futures-util = "0.3"

# Time and UUID
chrono = { version = "0.4", features = ["serde"] }
uuid = { version = "1.0", features = ["v4", "serde"] }

# Mobile optimization
parking_lot = "0.12"
dashmap = "5.5"
lru = "0.12"

# ZK proof libraries (lightweight)
ark-ff = "0.4"
ark-ec = "0.4"
ark-std = "0.4"

[dev-dependencies]
tempfile = "3.8"
criterion = "0.5"

[[bin]]
name = "zklock_mobile_demo"
path = "src/bin/zklock_mobile_demo.rs"

# Additional binaries can be added here when implemented
# [[bin]]
# name = "iot_gateway_server"
# path = "src/bin/iot_gateway_server.rs"
#
# [[bin]]
# name = "test_zk_merkle"
# path = "src/bin/test_zk_merkle.rs"

[features]
default = ["mobile-optimized"]
mobile-optimized = []
iot-gateway = []
full-node = []
