[package]
name = "da-sampler"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { workspace = true }
anyhow = { workspace = true }
rand = "0.8"

[[bin]]
name = "da-sampler"
path = "src/main.rs"
