[package]
name = "bpi-consensus"
version = "0.1.0"
edition = "2021"
description = "BLS commit objects and consensus primitives for BPI Mesh"

[dependencies]
# Core dependencies
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"
tracing = "0.1"

# BPI dependencies
bpi-enc = { path = "../../metanode-security/bpi-enc" }
bpi-blsagg = { path = "../../blsagg" }
bpi-validator-set = { path = "../bpi-validator-set" }
bpi-headers = { path = "../bpi-headers" }

[dev-dependencies]
tokio-test = "0.4"
proptest = "1.0"
