apiVersion: 1

datasources:
  # Prometheus - Primary metrics source
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true

  # Loki - Log aggregation
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    editable: true

  # External BPCI Server JSON API
  - name: BPCI Server
    type: grafana-simple-json-datasource
    access: proxy
    url: http://your-server.com:8081
    basicAuth: false
    editable: true
    jsonData:
      httpMethod: GET
      timeout: 30
