[package]
name = "bpci-enc"
version = "0.1.0"
edition = "2021"
description = "Canonical encoding library for BPI Mesh with domain-separated hashing"

[dependencies]
serde = { workspace = true }
serde_cbor = { workspace = true }
prost = { workspace = true }
blake3 = "1.5"
anyhow = { workspace = true }
thiserror = "1.0"
tokio = { version = "1.0", features = ["full"] }
tracing = { workspace = true }
ed25519-dalek = { version = "2.0", features = ["rand_core"] }
hex = "0.4"
uuid = { version = "1.0", features = ["v4", "serde"] }
chrono = { version = "0.4", features = ["serde"] }
rand = "0.8"
serde_json = { workspace = true }

[dev-dependencies]
proptest = { workspace = true }
criterion = { workspace = true }
serde_json = { workspace = true }

[[bench]]
name = "encoding_bench"
harness = false

[features]
default = []
std = []
