[package]
name = "vpods-daemon"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }
tokio = { workspace = true, features = ["full"] }
uuid = { workspace = true }
vpods-core = { path = "../../crates/vpods-core" }
vpods-agent = { path = "../../crates/vpods-agent" }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
blake3 = { workspace = true }
hex = { workspace = true }
