[package]
name = "networking"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "P2P networking layer shared between BPI Core and BPCI Enterprise"

[dependencies]
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
futures.workspace = true
async-trait.workspace = true
hyper.workspace = true
uuid.workspace = true
