[package]
name = "bpi-polar-proofs"
version = "0.1.0"
edition = "2021"
description = "Revolutionary Merkle + Polar Proofs with constant-size proofs and self-healing capabilities"
authors = ["BPI Core Team"]

[dependencies]
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
sha2 = "0.10"
hex = "0.4"
uuid = { version = "1.0", features = ["v4", "serde"] }
tokio = { version = "1.0", features = ["full"] }
tracing = "0.1"
# bpi-merkle = { path = "../../../../shared/crates/crypto-primitives" }
# bpi-enc = { path = "../../metanode-security/bpi-enc" }

# For polynomial mathematics and finite field arithmetic
num-bigint = "0.4"
num-traits = "0.2"
rand = "0.8"

[dev-dependencies]
proptest = "1.0"
criterion = "0.5"

# [[bench]]
# name = "polar_proof_benchmarks"
# harness = false

[features]
default = ["std"]
std = []
no_std = []
